### ISSUE TITLE
Installing JuliaExcel Erroring

### ISSUE THREAD

**Issue by chris-hampel-CA** [PGS62/JuliaExcel.jl#14]
Hello,

I was following the installation steps with Excel closed. After executing `JuliaExcel.installme()`. I see a message that says the `Installer script has been launched, please respond to the dialogs there`. However, I see what appears to be an error message show up. 

![image](https://user-images.githubusercontent.com/92957241/216727011-5d246207-c33d-4d83-8bbd-57b04e496f4f.png)

When I open excel and type `=Julia` in Excel it is not recognizing the command so I assume the installation did not occur correctly. 
Am I missing a step? Any other ideas why the installation would have errored?

Thanks, Chris

**Comment by PGS62** [comment]
I don't think you're "missing a step". What appears to be happening is that the install script is failing quite early, at the point when it's trying to detect whether or not Excel is already running. The offending code is a method called `CheckExcel` that calls a method `IsProcessRunning` that I think I cribbed from [this StackOverFlow post](https://stackoverflow.com/questions/19794726/vb-script-how-to-tell-if-a-program-is-already-running).

Here's a very hacky solution that _might_ work:
1) Ensure that Excel is _really_ not running - preferably using TaskManager to check that no "ghost" Excel process is running.
2) Open C:\Users\Christopher Hampel\.julia\packages\JuliaExcel\Y1cgX\Installer\install.vbs
(which is a copy of [this file](https://github.com/PGS62/JuliaExcel.jl/blob/e1424ab454334bb50bcbd15f44ceb372f27e48a0/installer/Install.vbs#L458)) in a text editor.
3) Comment out line 458 (a call to `CheckExcel`) by typing a single quote character at the start of the line.
4) Save the file.
5) Run the amended file by double-clicking it in file explorer.

Good luck!

**Comment by chris-hampel-CA** [comment]
Thanks for the suggestion @PGS62 . I attempted this after a restart of my computer, with no instance of Excel showing in the Task Manager, and found a new error occurring

![image](https://user-images.githubusercontent.com/92957241/218529268-3c599364-bd78-4a5a-ab6a-0d09eabda675.png)

Can you verify that line 458 is the correct line to make the comment on? I used the single quote to comment next to the beginning of the text in line 458.

![image](https://user-images.githubusercontent.com/92957241/218530537-b920c4d0-8a52-4c12-8da8-ee3ce0978f60.png)

**Comment by PGS62** [comment]
Ah sorry, I must have been looking at an out of date copy of `install.vbs`. You should comment out line 449.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/18028484/218688832-e3ae9120-8d6f-4fbf-b83e-c55e401efb58.png">

**Comment by chris-hampel-CA** [comment]
Ok thanks. Your suggestion for commenting out line 449 allowed me to complete the installation successfully! I don't know if this is a global issue or just local to me. I will let you decide how you want to handle it going forward. The issue can certainly be closed. 

Also, while I have you here, I have two more quick questions about this tool (as I'm really excited to use this in hopes to allow non-coders to interface with julia tools that I work on) 

1. I want to make julia functions that are specific to a project available to be called with `JuliaCall`. I originally added the JuliaExcel package to a project env and did the installation; however, when opening Excel, I could only call `=JuliaLaunch()` successfully if I added the JuliaExcel package to my base env. How can I launch a JuliaExcel session in Excel such that it calls julia in a project env?
3. Also in testing this, I noticed that if I run some simple `=JuliaEval()` expressions when working in my base env, the correct outputs appear in Excel as expected, but when I close and re-open the same file, the outputs go away. They re-appear if we launch julia again and press enter again in all the cells with `JuliaEval` calls. My question: is there a way to make the julia outputs stay visible when re-opening Excel such that a `JuliaEval` expression can be evaluated only once? My use case is: I want to call a function that runs a model and displays the resulting data such that when I close Excel and re-open, my previous model run's data is still available for viewing. The data could then only be overwritten by re-launching Julia and evaluating the expressions again.

Thanks, Chris

**Comment by PGS62** [comment]
The failure of the installer script on your PC was a surprise to me - I'd not seen that before. Is your PC "locked down" in some way, perhaps by a corporate IT department (anti-virus etc.)?

In answer to your questions:

1) `JuliaLaunch` has a `CommandLineOptions` argument. I think that you should be able to pass `"--project c:/path/to/environment"` as that argument and things should work as you want them to. (Note unix-style forward slashes in the path!) See [command-line switches for Julia](https://docs.julialang.org/en/v1/manual/command-line-options/). I have not tested this today (and it's a while since I worked on JuliaExcel) so please let me know how you get on with this suggestion.

2) To investigate I did the following
a) opened a new workbook
b) switched Excel calculation to Automatic
c) entered formula `=JuliaLaunch()` in cell A1
d) entered formula `=JuliaEval("1:100")` in A2 - to populate cells A2 to A101
e) Saved, closed and reopened the workbook
f) Observed that A2 to A101 were still populated.

I then put a breakpoint in the VBA code of `JuliaEval` and discovered that when re-opening the workbook `JuliaEval` is called. I think this means that Excel is treating cell A2 as containing a "volatile" formula. So I think MANUAL calculation is your best bet.

**Comment by PGS62** [comment]
No, `JuliaEval` certainly can't "return a plot" in the sense that a VBA function (which `juliaeval` is) cannot return an Excel chart when called from an Excel worksheet.

I think you have two options:

1. Have your Julia function return data to the worksheet and use Excel's charting functionality to plot it.
2. Have your Julia function generate a plot, save that plot to file (say in .svg) format and write code in the `Worksheet_Calculate` event of the worksheet's class module that inserts a picture into the sheet, based on that .svg file. I would only attempt this option if the plot\chart you want to generate is of a kind that's beyond Excel's capability. It's also a question of how much experience of VBA you have.

**Comment by chris-hampel-CA** [comment]
That makes sense. Thanks for all the help, again.
